config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :spaces

  namespace :admin do

    get 'login', to: 'sessions#new'
    post 'login', to: "sessions#create"
    delete "sign_out", to: "sessions#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feature.rb
# == Schema Information
#
# Table name: features
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Feature < ApplicationRecord
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end

end

app/models/feature_mapping.rb
# == Schema Information
#
# Table name: feature_mappings
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  feature_id :bigint           not null
#  space_id   :bigint           not null
#
# Indexes
#
#  index_feature_mappings_on_feature_id               (feature_id)
#  index_feature_mappings_on_feature_id_and_space_id  (feature_id,space_id) UNIQUE
#  index_feature_mappings_on_space_id                 (space_id)
#
# Foreign Keys
#
#  fk_rails_...  (feature_id => features.id)
#  fk_rails_...  (space_id => spaces.id)
#
class FeatureMapping < ApplicationRecord
  belongs_to :feature
  belongs_to :space
end

app/models/space.rb
# == Schema Information
#
# Table name: spaces
#
#  id              :bigint           not null, primary key
#  address         :string(255)
#  description     :text(65535)      not null
#  latitude        :float(24)
#  longitude       :float(24)
#  name            :string(255)      not null
#  nearest_station :string(255)
#  rating          :integer          default(2)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Space < ApplicationRecord
  has_many_attached :images
  has_many :space_type_mappings, dependent: :destroy
  has_many :space_types, through: :space_type_mappings
  has_many :feature_mappings, dependent: :destroy
  has_many :features, through: :feature_mappings

  validates :name, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5, only_integer: true }

  def main_image
    images.first || 'http://placehold.jp/300x200.png'
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "description", "name", "nearest_station"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["space_types", "features"]
  end

end

app/models/space_type.rb
# == Schema Information
#
# Table name: space_types
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class SpaceType < ApplicationRecord
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["id"]
  end
end

app/models/space_type_mapping.rb
# == Schema Information
#
# Table name: space_type_mappings
#
#  id            :bigint           not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  space_id      :bigint           not null
#  space_type_id :bigint           not null
#
# Indexes
#
#  index_space_type_mappings_on_space_id                    (space_id)
#  index_space_type_mappings_on_space_type_id               (space_type_id)
#  index_space_type_mappings_on_space_type_id_and_space_id  (space_type_id,space_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (space_id => spaces.id)
#  fk_rails_...  (space_type_id => space_types.id)
#
class SpaceTypeMapping < ApplicationRecord
  belongs_to :space_type
  belongs_to :space
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    if user_signed_in?
      redirect_to root_path, info: "既にログインしています"
    end
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.admin? && user.valid_password?(params[:password])
      sign_in(user)
      redirect_to root_path, success: "ログインしました"
    else
      flash.now[:error] = "ログイン失敗"
      render :new, status: :unauthorized
    end
  end

  def destroy
    sign_out :user
    redirect_to root_path, info: "ログアウトしました"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  add_flash_types :info, :success, :warning, :error
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Space.ransack(params:[:q])
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Space.ransack(params[:q])
    @pagy, @spaces = pagy(@q.result.with_attached_images.includes(:features).order(created_at: :desc))
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    if @space.save
      redirect_to @space, success: "成功しました"
    else
      flash.now[:error] = "失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @space = Space.with_attached_images.find(params[:id])
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    space = Space.find(params[:id])
    if space.update(space_params)
      redirect_to space, success: "更新しました"
    else
      flash.now[:error] = "失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # レコードを１つ削除
  end

  private
  
  def space_params
    params.require(:space).permit(
      :name, :description, :address, :nearest_station, {space_type_ids:[]}, :longitude, :latitude, {feature_ids: []}, {images: []}, :rating)
  end

  def check_admin
    redirect_to(root_path, error: "権限がありません") unless current_user&.admin?
  end

end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/home/index.html.erb
<div class="hero min-h-screen" style="background-image: url(<%= asset_url('hero.jpg') %>);">
  <div class="hero-overlay bg-opacity-60"></div>
  <div class="hero-content text-center text-neutral-content">
    <%= render 'shared/search_form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>開発版</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script>
      (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
        key: '<%= Rails.application.credentials.google[:api_map_key] %>',
        v: "weekly",
        // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
        // Add other bootstrap parameters as needed, using camel case.
      });
    </script>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash/flash' %>
    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer p-10 bg-neutral text-neutral-content">
  <aside>
    <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>ACME Industries Ltd.<br>Providing reliable tech since 1992</p>
  </aside> 
  <nav>
    <h6 class="footer-title">Social</h6> 
    <div class="grid grid-flow-col gap-4">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <%= link_to root_path, class:"btn btn-ghost text-xl" do %>
      開発開発開発開発開発開発開発
    <% end %>
  </div>
  <div class="navbar-end">
    <div>
      <% if current_user&.admin? %>
        <%= link_to new_space_path, class: "btn btn-primary" do %>
          + NEW SPACE
        <% end %>
      <% end %>
    </div>
    <div>
      <a class="btn btn-ghost btn-circle">
        <div class="indicator">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
          <span class="badge badge-xs badge-primary indicator-item"></span>
        </div>
      </a>
    </div>
    <div class="dropdown dropdown-end flex">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <img alt="Tailwind CSS Navbar component" src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
        </div>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <% if user_signed_in? %>
          <li><%= button_to "ログアウト", destroy_user_session_path , method: :delete, data: { turbo_method: :delete } %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.erb
<%= search_form_for @q, url: spaces_path do |form| %>
  <div class="flex gap-[30px]">
    <div class="w-[200px]">
      <%= form.collection_select :space_types_id_eq, SpaceType.all, :id, :name, {include_blank: '会場タイプ'}, {class: "select select-bordered w-full max-w-xs"} %>
    </div>
    <div class="w-[300px]">
      <%= form.text_field :name_or_description_or_address_or_nearest_station_cont, class: 'input input-bordered w-full max-w-xs', placeholder:"キーワード" %>
    </div>
    <div>
      <label for="my_modal_6" class="btn btn-active">こだわり条件</label>
      <input type="checkbox" id="my_modal_6" class="modal-toggle" />
      <div class="modal" role="dialog">
        <div class="modal-box">
          <h3 class="font-bold text-lg text-center">こだわり条件</h3>
          <div class="w-[400px] flex flex-wrap">
            <%= form.collection_check_boxes :features_id_eq_any, Feature.all, :id, :name do |b| %>
            <div class="form-control mr-2">
              <%= b.label class: "label cursor-pointer" do %>
                <span class="label-text"><%= b.text %></span>
                <span class="inline-block w-[10px]"></span>
                <%= b.check_box class: "checkbox checkbox-primary" %>
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="modal-action">
            <label for="my_modal_6" class="btn">決定</label>
          </div>
        </div>
      </div>
    </div>
    <div>
      <%= form.submit class: "btn btn-primary", value: 'SEARCH!' %>
    </div>
  </div>
<% end %>

app/views/shared/flash/_alert.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>

app/views/shared/flash/_error.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>

app/views/shared/flash/_flash.html.erb
<div class="m-10">
  <% flash.each do |message_type, message| %>
    <% 
      message_type = 'success' if message_type == 'notice'
      message_type = 'error' if message_type == 'alert'
    %>
    <div role="alert" class="alert alert-<%= message_type %> justify-start">
      <%= message_type %>
      <%= render "shared/flash/#{message_type}" %>
      <span><%= message %></span>
    </div>
  <% end %>
</div>

app/views/shared/flash/_info.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>

app/views/shared/flash/_notice.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>

app/views/shared/flash/_success.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>

app/views/shared/flash/_warning.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>

app/views/spaces/_form.html.erb
  <%= form_with model:space, data:{controller:'set-map'}, local: false do |form| %>

    <%= form.label :name, class:"form-control w-full max-w-xs" do %>
      <div class="label"><span class="label-text">Name</span></div>
      <%= form.text_field :name, class: 'input input-bordered w-full max-w-xs' %>
    <% end %>

    <%= form.label :rating, class:"form-control w-full max-w-xs" do %>
      <div class="label"><span class="label-text">Rating</span></div>
      <div class="rating">
        <% 5.times do |index| %>
          <%= form.radio_button :rating, index + 1, class:"mask mask-star-2 bg-orange-400", checked: index == space.rating %>
        <% end %>
      </div>
    <% end %>

    <%= form.label :description, class:"form-control w-full max-w-xs" do %>
      <div class="label"><span class="label-text">Description</span></div>
      <%= form.text_field :description, class: 'input input-bordered w-full max-w-xs' %>
    <% end %>

    <%= form.label :address, class:"form-control w-full max-w-xs" do %>
      <div class="label"><span class="label-text">Address</span></div>
      <%= form.text_field :address, class: 'input input-bordered w-full max-w-xs' %>
    <% end %>

    <%= form.label :nearest_station, class: 'form-control w-full max-w-xs' do %>
      <div class="label"><span class="label-text">Nearest station</span></div>
      <%= form.text_field :nearest_station, class: 'input input-bordered w-full max-w-xs' %>
    <% end %>

    <%= form.label :space_types, class: 'form-control w-full max-w-xs' do %>
      <div class="label"><span class="label-text">Space Types</span></div>
      <%= form.collection_select :space_type_ids, SpaceType.all, :id, :name, {include_blank: "会場タイプ"}, {class: "select select-bordered w-full max-w-xs", multiple:true} %>
    <% end %>

    <%= form.label :features, class: 'form-control w-full max-w-xs' do %>
      <div class="label"><span class="label-text">Features</span></div>
      <%= form.collection_check_boxes :feature_ids, Feature.all, :id, :name do |b| %>
        <div class="form-control mr-2">
          <%= b.label class: "label cursor-pointer" do %>
            <span class="label-text"><%= b.text %></span>
            <span class="inline-block w-[10px]"></span>
            <%= b.check_box class: "checkbox checkbox-primary" %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <div class="flex gap-5 mb-5">
      <%= form.label :latitude, class: 'form-control w-full max-w-xs' do %>
        <div class="label"><span class="label-text">Latitude</span></div>
        <%= form.text_field :latitude, class: 'input input-bordered w-full max-w-xs', readonly:true, data:{ "set-map-target":"latitude" } %>
      <% end %>

      <%= form.label :longitude, class: 'form-control w-full max-w-xs' do %>
        <div class="label"><span class="label-text">Longitude</span></div>
        <%= form.text_field :longitude, class: 'input input-bordered w-full max-w-xs', readonly:true, data:{ "set-map-target":"longitude" } %>
      <% end %>
    </div>

    <p>クリックしてピンを立ててください</p>
    <div data-set-map-target="map" class="h-[500px] mb-5"></div>

    <%= form.label :images, class: 'form-control w-full max-w-xs' do %>
      <div class="label"><span class="label-text">Images</span></div>
      <%= form.file_field :images, multiple: true %>
    <% end %>

    <%= form.submit class:"btn btn-primary" %>

  <% end %>

app/views/spaces/_space.html.erb
<%= link_to space_path(space) do %>
  <div class="card card-side bg-base-100 shadow-xl">
    <figure class="w-[200px]"><%= image_tag space.main_image, size: '400x225' %></figure>
    <div class="card-body">
      <h2 class="card-title"><%= space.name %></h2>
      <div class="flex mb-[5px]">
        <span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
          </svg>
        </span>
        <span><%= space.nearest_station %></span>
      </div>
      <div class="flex mb-[5px]">
        <span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
          </svg>
        </span>
        <span><%= space.address %></span>
      </div>
      <div class="flex mb-[5px]">
        <% space.features.each do |feature| %>
          <div class="badge badge-outline">
            <%= feature.name %>
          </div>
        <% end %>
      </div>
      <div class="rating">
        <% space.rating.times do %>
          <div class="mask mask-star-2 bg-orange-400 w-[20px] h-[20px]"></div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<div class="w-[800px] mx-auto my-[100px]">
  <%= render 'form', space: @space %>
</div>

app/views/spaces/index.html.erb
<div class="my-[150px]">

  <div class="flex items-center justify-center mb-[100px]">
    <%= render 'shared/search_form' %>  
  </div>
  <div>
    <div class="max-w-[800px] mx-auto">
      <div class="flex items-center justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
      <div class="py-[50px]">
        <%= render @spaces %>
      </div>
      <div class="flex items-center justify-center">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="w-[800px] mx-auto my-[100px]">
    <div class="mb-5">
      <% if current_user&.admin? %>
        <%= link_to edit_space_path, class: "btn btn-secondary" do %>
          Edit SPACE
        <% end %>
      <% end %>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Name</span></div>
      <div class="text-xl p-2"><%= @space.name %></div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Rating</span></div>
      <div class="rating">
        <% @space.rating.times do %>
          <div class="mask mask-star-2 bg-orange-400 w-[20px] h-[20px]"></div>
        <% end %>
      </div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Description</span></div>
      <div class="text-xl p-2"><%= @space.description %></div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Address</span></div>
      <div class="text-xl p-2"><%= @space.address %></div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Nearest station</span></div>
      <div class="text-xl p-2"><%= @space.nearest_station %></div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Space Types</span></div>
      <div>
        <ul>
          <% @space.space_types.each do |space_type| %>
            <li class="text-xl p-2"><%= space_type.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="form-control w-full max-w-xs">
      <div class="label"><span class="label-text">Features</span></div>
      <div>
        <ul>
          <% @space.features.each do |feature| %>
            <li class="text-xl p-2"><%= feature.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div data-controller="show-map" 
      data-show-map-latitude-value="<%= @space.latitude %>"
      data-show-map-longitude-value="<%= @space.longitude %>"
      class="h-[500px] my-5">
    </div>

  <div class="carousel carousel-center rounded-box">
    <% @space.images.each do |image| %>
      <div class="carousel-item">
        <%= image_tag image, class:'w-full' %>
      </div>
    <% end %>
  </div>

</div>